export const person: Person = {
  id: 1,
  name: 'Pranav Arora',
  phone: '9586342174',
  dob: new Date('2000-12-18'),
  dobType: 'Exact',
  addressLine1: '123, Main Street',
  city: 'City',
  addressLine2: 'Near Landmark',
  state: 'Gujarat',
  country: 'India',
  pincode: '380001',
  gender: 'Male',
  isNodal: false,
  landmark: 'Near Landmark',
  thalassemiaStatus: 'Unknown',
  relationship: null,
  relatives: [
    {
      id: 2,
      name: 'Pankaj Arora',
      phone: '9586342174',
      dob: new Date('2000-12-18'),
      dobType: 'Exact',
      addressLine1: '123, Main Street',
      city: 'City',
      addressLine2: 'Near Landmark',
      state: 'Gujarat',
      country: 'India',
      pincode: '380001',
      gender: 'Male',
      isNodal: false,
      landmark: 'Near Landmark',
      relationship: 'parent',
      thalassemiaStatus: 'Unknown',
      relatives: [
        {
          id: 5,
          name: 'Keval Kumar Arora',
          phone: '9586342174',
          dob: new Date('2000-12-18'),
          dobType: 'Exact',
          addressLine1: '123, Main Street',
          city: 'City',
          addressLine2: 'Near Landmark',
          state: 'Gujarat',
          country: 'India',
          pincode: '380001',
          gender: 'Male',
          isNodal: false,
          landmark: 'Near Landmark',
          relationship: 'parent',
          thalassemiaStatus: 'Unknown',
          relatives: [
            {
              id: 6,
              name: 'Hamesh Arora',
              phone: '9586342174',
              dob: new Date('2000-12-18'),
              dobType: 'Exact',
              addressLine1: '123, Main Street',
              city: 'City',
              addressLine2: 'Near Landmark',
              state: 'Gujarat',
              country: 'India',
              pincode: '380001',
              gender: 'Male',
              isNodal: false,
              landmark: 'Near Landmark',
              relationship: 'sibling',
              thalassemiaStatus: 'Unknown',
              relatives: [
                {
                  id: 7,
                  name: 'Sudha Arora',
                  phone: '9586342174',
                  dob: new Date('2000-12-18'),
                  dobType: 'Exact',
                  addressLine1: '123, Main Street',
                  city: 'City',
                  addressLine2: 'Near Landmark',
                  state: 'Gujarat',
                  country: 'India',
                  pincode: '380001',
                  gender: 'Female',
                  isNodal: false,
                  landmark: 'Near Landmark',
                  relationship: 'spouse',
                  thalassemiaStatus: 'Unknown',
                  relatives: [],
                },
              ],
            },
          ],
        },
        {
          id: 6,
          name: 'Raj Arora',
          phone: '9586342174',
          dob: new Date('2000-12-18'),
          dobType: 'Exact',
          addressLine1: '123, Main Street',
          city: 'City',
          addressLine2: 'Near Landmark',
          state: 'Gujarat',
          country: 'India',
          pincode: '380001',
          gender: 'Female',
          isNodal: false,
          landmark: 'Near Landmark',
          relationship: 'parent',
          thalassemiaStatus: 'Unknown',
          relatives: [],
        },
      ],
    },
    {
      id: 3,
      name: 'Neelima Arora',
      phone: '9586342174',
      dob: new Date('2000-12-18'),
      dobType: 'Exact',
      addressLine1: '123, Main Street',
      city: 'City',
      addressLine2: 'Near Landmark',
      state: 'Gujarat',
      country: 'India',
      pincode: '380001',
      gender: 'Female',
      isNodal: true,
      landmark: 'Near Landmark',
      relationship: 'parent',
      thalassemiaStatus: 'Unknown',
      relatives: [],
    },
    {
      id: 4,
      name: 'Abhishek Arora',
      phone: '9586342174',
      dob: new Date('2000-12-18'),
      dobType: 'Exact',
      addressLine1: '123, Main Street',
      city: 'City',
      addressLine2: 'Near Landmark',
      state: 'Gujarat',
      country: 'India',
      pincode: '380001',
      gender: 'Male',
      isNodal: false,
      landmark: 'Near Landmark',
      relationship: 'sibling',
      thalassemiaStatus: 'Unknown',
      relatives: [],
    },
  ],
};
